name: ROS CI

on:
  push:
    branches: [ $default-branch ]

jobs:
  build_docker:
    runs-on: ubuntu-xenial
    container:
      image: ubuntu:xenial
    steps:
      - uses: ros-tooling/setup-ros@0.0.25
        with:
          required-ros-distributions: kinetic
      - run: "source /opt/ros/kinetic/setup.bash && rosnode --help"
